-- !Ups

CREATE TABLE TASKS (
    NAME varchar(30)  NOT NULL,
    PARENT_NAME varchar(30)  NULL,
    USERNAME varchar(30)  NOT NULL,
    CONSTRAINT task_pk PRIMARY KEY (NAME, PARENT_NAME, USERNAME)
);

CREATE TABLE SESSIONS (
    TOKEN varchar(30)  NOT NULL,
    USERNAME varchar(30)  NOT NULL,
    EXPIRATION_DATE timestamp  NOT NULL,
    CONSTRAINT task_time_pk PRIMARY KEY (TOKEN)
);

CREATE TABLE USERS (
    LOGIN varchar(30)  NOT NULL,
    PASSWORD varchar(30)  NOT NULL,
    CONSTRAINT user_pk PRIMARY KEY (LOGIN)
);

-- foreign keys
ALTER TABLE TASKS ADD CONSTRAINT TASKS_TASKS
    FOREIGN KEY (PARENT_NAME, USERNAME)
    REFERENCES TASKS (NAME, USERNAME)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE SESSIONS ADD CONSTRAINT SESSIONS_USER
    FOREIGN KEY (USERNAME)
    REFERENCES USERS (LOGIN)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

ALTER TABLE TASKS ADD CONSTRAINT USERS_TASKS
    FOREIGN KEY (USERNAME)
    REFERENCES USERS (LOGIN)
    NOT DEFERRABLE
    INITIALLY IMMEDIATE
;

-- !Downs

DROP TABLE USERS;
DROP TABLE SESSIONS;
DROP TABLE TASKS;